### ISSUE TITLE
Sending email when job finishes not working when mail server has restrictions for "FROM" addresses

### ISSUE THREAD

**Issue by danieldefrancisco-lr** [wandjini/Dl-Cleaner#5]
Their mail server only accepts sending emails from a ...@cantabria.es email address, so this feature is not gonna work for them, unless we change the hardcoded "from" address, or if the from address could be set as a property

**Comment by wandjini** [comment]
I sent a new version that used the email in the portlet properties file

**Comment by wandjini** [comment]
Mange default sender and receiver in the properties
